server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/personneldb
    username: app
    password: app

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

