server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/personneldb
    username: app
    password: app

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

info:
  app:
    name: personnel-service
    description: Personnel microservice for internship project
    version: @project.version@

app:
  security:
    basic:
      username: admin
      password: admin123
